Disable Pharo testing for the moment, not sure what the issue is
The following stack trace is reported:

```
Error: Can't find the requested origin
        UnixResolver(PlatformResolver)>>cantFindOriginError
        [ self cantFindOriginError ] in UnixResolver(PlatformResolver)>>directoryFromEnvVariableNamed: in Block: [ self cantFindOriginError ]
        UnixResolver(PlatformResolver)>>directoryFromEnvVariableNamed:or:
        UnixResolver(PlatformResolver)>>directoryFromEnvVariableNamed:
        UnixResolver>>home
```

But since we still have Squeak, which seems to work, I’ll disable Pharo for the moment.

Signed-off-by: Stefan Marr <git@stefan-marr.de>